// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SinhVien.Models;

namespace SinhVien.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20181124052144_adsad")]
    partial class adsad
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SinhVien.Models.KetQua", b =>
                {
                    b.Property<string>("MaKQ")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Diem");

                    b.Property<string>("MaMon");

                    b.Property<string>("MaSV");

                    b.HasKey("MaKQ");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaSV");

                    b.ToTable("KetQuas");
                });

            modelBuilder.Entity("SinhVien.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TenKhoa")
                        .IsRequired();

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("SinhVien.Models.MonHoc", b =>
                {
                    b.Property<string>("MaMon")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SoTinChi");

                    b.Property<string>("TenMmon");

                    b.HasKey("MaMon");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("SinhVien.Models.SinhVient", b =>
                {
                    b.Property<string>("MaSV")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DiaChi");

                    b.Property<string>("MaKhoa");

                    b.Property<string>("MaMon");

                    b.Property<DateTime>("NgaySinh");

                    b.Property<string>("TenSV")
                        .IsRequired();

                    b.HasKey("MaSV");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("MaMon");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("SinhVien.Models.KetQua", b =>
                {
                    b.HasOne("SinhVien.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMon");

                    b.HasOne("SinhVien.Models.SinhVient", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSV");
                });

            modelBuilder.Entity("SinhVien.Models.SinhVient", b =>
                {
                    b.HasOne("SinhVien.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa");

                    b.HasOne("SinhVien.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMon");
                });
#pragma warning restore 612, 618
        }
    }
}
